is-prd: true
#服务相关配置
server: 
#HTTP端口
  port: 8088
  session:  
    #session超时时间，单位秒
    timeout:  3600
      
spring:
  #集群session存储方式
  session:  
    store-type: none  
  #数据源
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://rm-uf6bdv92a95017474oo.mysql.rds.aliyuncs.com:3306/phweb?useUnicode=true&amp;characterEncoding=utf-8
    username:  puhao
    password:  Puhao2018
    driverClassName:  com.mysql.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize:  5
    minIdle:  5
    maxActive:  20
    #配置获取连接等待超时的时间
    maxWait:  60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis:  60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #校验SQL，Oracle配置     validationQuery:  SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:  stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat:  true
#jpa相关配置
  jpa:  
  #是否自动生成/修改数据库表
    show-sql: true
    generate-ddl: false
  http:
    multipart:
      max-file-size: 10MB   
ph: 
  default:  
    #默认密码
    pwd: 123456
  file: 
    path: /usr/local/images/product
    server: https://pic.offway.cn:8443/images/product
  url: https://zeus.offway.cn
qiniu:
  url: http://qiniu.offway.cn
  access-key: WU33Cpp1WJZAf4oIIHknc2ga3ZhQpgJo3UL-JUdB
  secret-key: ALb95JFSVi3mvSScoQa564HzDby_y2EasUhhmniV
  bucket: offwaypro
#极光推送
jpush:
  apns-production: true
  app-key: 23f3d1476579eda19a0da872
  master-secret: 90f4a69575d4a51c877f5dad
#美洽客服配置
meqia:  
  key:  $2a$12$DH0LKaxq.alh49rSMkOP0eaEfZzcwUb95Wg6cY5DTLRvI.CG6vZNi
#浏览器环境配置项，参见BrowserProperties
vinann:
  security: 
    browser:
      signInPage: /login.html
      signInResponseType: JSON
      singInSuccessUrl: /
      #rememberMeSeconds: 294000
      signOutUrl: /login.html
      session:  
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /login.html
     