debug: true
#服务相关配置
server: 
#HTTP端口
  port: 8088
  session:  
    #session超时时间，单位秒
    timeout:  3600     
spring:
  #集群session存储方式
  session:  
    store-type: none   
  #数据源
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://rm-uf6bdv92a95017474oo.mysql.rds.aliyuncs.com:3306/phweb_dev?useUnicode=true&amp;characterEncoding=utf-8
    username:  puhao
    password:  Puhao2018
    driverClassName:  com.mysql.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize:  5
    minIdle:  5
    maxActive:  20
    #配置获取连接等待超时的时间
    maxWait:  60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis:  60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #校验SQL，Oracle配置     validationQuery:  SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:  stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat:  true
#jpa相关配置
  jpa:  
  #是否自动生成/修改数据库表
    show-sql: true
    generate-ddl: false
  http:
    multipart:
      max-file-size: 10MB
      
ph: 
  default:  
    #默认密码
    pwd: 123456
  file: 
    path: D:/workspace/hades/src/main/resources/static
    server: http://127.0.0.1:8088
qiniu:
  url: http://qiniu.offway.cn
  access-key: WU33Cpp1WJZAf4oIIHknc2ga3ZhQpgJo3UL-JUdB
  secret-key: ALb95JFSVi3mvSScoQa564HzDby_y2EasUhhmniV
  bucket: offwaypro
#极光推送
jpush:
  apns-production: false
  app-key: 23f3d1476579eda19a0da872
  master-secret: 90f4a69575d4a51c877f5dad
#美洽客服配置
meqia:  
  key:  $2a$12$DH0LKaxq.alh49rSMkOP0eaEfZzcwUb95Wg6cY5DTLRvI.CG6vZNi
#浏览器环境配置项，参见BrowserProperties
vinann:
  security: 
    browser:
      signInPage: /login.html
      signInResponseType: JSON
      singInSuccessUrl: /
      #rememberMeSeconds: 294000
      signOutUrl: /login.html
      #signUpUrl: /register.html

#session管理相关配置，参见SessionProperties
      session:  
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /login.html

#图片验证码配置项，参见ImageCodeProperties
#vinann.security.code.image.length = 4
#vinann.security.code.image.width = 100
#vinann.security.code.image.height = 30
#vinann.security.code.image.expireIn = 30
#    code: 
#      image:  
#        url: /code/sms

#短信验证码配置项，参见SmsCodeProperties
#vinann.security.code.sms.length = 6
#vinann.security.code.sms.expireIn = 60
#      sms:  
#        url: /user/regist

#社交登录功能拦截的url,参见SocialProperties
#vinann.security.social.filterProcessesUrl = /qqLogin

#QQ登录配置，参见QQProperties
#vinann.security.social.qq.app-id = 101496570
#vinann.security.social.qq.app-secret = 8bb3dceb6deee36c9cf94f8450f45d1a
#vinann.security.social.qq.providerId = qq

#微信登录配置，参见WeixinProperties
#vinann.security.social.weixin.app-id = wxd99431bbff8305a0
#vinann.security.social.weixin.app-secret = 60f78681d063590a469f1b297feff3c4
#vinann.security.social.weixin.providerId = weixin

#认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
#vinann.security.oauth2.clients[0].clientId = vinann
#vinann.security.oauth2.clients[0].clientSecret = vinannsecret
#vinann.security.oauth2.clients[0].accessTokenValidateSeconds = 3600
#vinann.security.oauth2.clients[1].clientId = test
#vinann.security.oauth2.clients[1].clientSecret = test

#OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
#vinann.security.oauth2.tokenStore = redis
#使用jwt时为token签名的秘钥
#vinann.security.oauth2.jwtSigningKey = vinann
#https://github.com/jojozhai/security
    